[deps]
C13NV = "136d2b59-c380-4582-9748-dc44afbd1b80"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"

[sources]
C13NV = {path = ".."}
